- name: Install nvm
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm.version }}
  tags: nvm

- name: Source nvm in ~/.profile
  lineinfile: >
    dest=~/.profile
    line="source ~/.nvm/nvm.sh"
  tags: nvm

- name: Source nvm in ~/.bashrc
  lineinfile: >
    dest=~/.bashrc
    line="source ~/.nvm/nvm.sh"
  tags: nvm

- name: Source nvm in ~/.zshrc
  lineinfile: >
    dest=~/.zshrc
    line="source ~/.nvm/nvm.sh"
  tags: nvm

- name: Install {{ nvm.node_version }}
  command: sudo -iu {{ nvm.user }} . ~/.nvm/nvm.sh && nvm install v{{ nvm.node_version }}
  tags: nvm

- name: Set default node version to {{ nvm.node_version }}
  command: sudo -iu {{ nvm.user }} . ~/.nvm/nvm.sh && nvm alias default v{{ nvm.node_version }}
  tags: nvm